// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdb9zaB-DNKVZOM2DVpcz_-mZVirst0J8',
    appId: '1:1006112758415:web:d8acbfd75b6cbf726e2efa',
    messagingSenderId: '1006112758415',
    projectId: 'mon-bang',
    authDomain: 'mon-bang.firebaseapp.com',
    storageBucket: 'mon-bang.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw8LaC8QSsza-NiDgto2wK3pwsZXP9Z2M',
    appId: '1:1006112758415:android:2ffe8582389d513c6e2efa',
    messagingSenderId: '1006112758415',
    projectId: 'mon-bang',
    storageBucket: 'mon-bang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABpPZokEy9p8itCA4IWBo-YQekVqXnKf4',
    appId: '1:1006112758415:ios:c655f6be77c696e86e2efa',
    messagingSenderId: '1006112758415',
    projectId: 'mon-bang',
    storageBucket: 'mon-bang.appspot.com',
    iosClientId: '1006112758415-3fo14md3n5pf6ggfmmchtu08niohqg54.apps.googleusercontent.com',
    iosBundleId: 'com.example.monbang',
  );
}
